### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException Unable to start activity ComponentInfo{com.instpower.global/com.stripe.android.view.PaymentFlowActivity}: java.lang.IllegalArgumentException: Required value was null.

### ISSUE THREAD

**Issue by DodoSpringLove** [stripe/stripe-react-native#1004]
**Describe the bug**
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.instpower.global/com.stripe.android.view.PaymentFlowActivity}: java.lang.IllegalArgumentException: Required value was null.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 Device
Brand:Google
Model:Pixel 3 XL
Orientation: Portrait
RAM free: 6.73 GB
Disk free: 14.79 GB
Operating System
Version:Android 9
Orientation: Portrait
Rooted:No
Crash
Date:Jun 21, 2022, 1:51:44 PM

    "@stripe/react-stripe-js": "^1.7.0",
    "@stripe/stripe-js": "^1.24.0",
    "@stripe/stripe-react-native": "0.2.1",

**Additional context**
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.instpower.global/com.stripe.android.view.PaymentFlowActivity}: java.lang.IllegalArgumentException: Required value was null.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by charliecruzan-stripe** [comment]
Closing since we need the template to be fully filled out in order to help with bug reports. Also, it looks like you're using a combo of React and React Native libraries, and your version of `stripe-react-native` is pretty old. Happy to help if you can provide a reproducible demo, though

**Comment by DodoSpringLove** [comment]
I also want to know how this problem happened, because this is the crash information of the package on Firebase, so I can only ask you for help, I can not judge from the log and can not reproduce, can you help to check? According to the Android native code, it is because the required parameters failed to be obtained, or the required parameters were not transmitted, but I do not know whether it occurred when tying the card or paying

**Comment by DodoSpringLove** [comment]
> Closing since we need the template to be fully filled out in order to help with bug reports. Also, it looks like you're using a combo of React and React Native libraries, and your version of `stripe-react-native` is pretty old. Happy to help if you can provide a reproducible demo, though
-------------------------------------------------------------
Can I upgrade this version to solve your problem?

**Comment by MaxJadav** [comment]
![Uploading Screenshot 2022-07-25 at 12.21.35 PM.png…]()
"@stripe/stripe-react-native": "^0.9.0"
Version:Android 9

**Comment by professorkolik** [comment]
Same here

"@stripe/stripe-react-native": "^0.9.0"
"react-native": "0.69.8"

Android 11

**Comment by charliecruzan-stripe** [comment]
Hi, can you try using the most recent version of `@stripe/stripe-react-native`?

**Comment by TrustDec** [comment]
It still happens in the latest version:
```shell
 Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.packagename/com.stripe.android.view.PaymentMethodsActivity}: java.lang.IllegalArgumentException: Required value was null.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by pankajsoftyoi** [comment]
Error:
java.lang.IllegalArgumentException - Required value was null.

Getting the same issue with this version also
"@stripe/stripe-react-native": "0.40.0",

<img width="981" height="499" alt="Image" src="https://github.com/user-attachments/assets/803adb4e-8346-4cdd-810a-726181514683" />

**Comment by jaynewstrom-stripe** [comment]
Hi all, please open a new issue with steps to reproduce. 

As for the most recent report, we have a test assuring we don't crash here, see https://github.com/stripe/stripe-android/blob/42e8ab0817fb1e0634c025022e6fa40066e14c37/paymentsheet/src/test/java/com/stripe/android/paymentsheet/addresselement/AddressElementActivityTest.kt#L14

I'm going to lock this conversation to ensure new reports are under new issues. Thanks!
