### ISSUE TITLE
IllegalStateException: Cannot remove Fragment attached to a different FragmentManager.

### ISSUE THREAD

**Issue by xiao555** [stripe/stripe-react-native#1053]
**Describe the bug**

Crash on Android when start the app:

```
java.lang.IllegalStateException: Cannot remove Fragment attached to a different FragmentManager. Fragment GooglePayPaymentMethodLauncherFragment{d79510a} (edd98127-8900-4dad-a833-af71fa4942e9 tag=google_pay_support_fragment) is already attached to a FragmentManager.
    at androidx.fragment.app.BackStackRecord.remove(BackStackRecord.java:204)
    at com.reactnativestripesdk.GooglePayPaymentMethodLauncherFragment.onViewCreated$lambda-1(GooglePayPaymentMethodLauncherFragment.kt:40)
    at com.reactnativestripesdk.GooglePayPaymentMethodLauncherFragment.$r8$lambda$Nsq6EBHcRzObOMQDgiGKkd4TR7E
    at com.reactnativestripesdk.GooglePayPaymentMethodLauncherFragment$$ExternalSyntheticLambda0.onReady
    at com.stripe.android.googlepaylauncher.GooglePayPaymentMethodLauncher$5.invokeSuspend(GooglePayPaymentMethodLauncher.kt:205)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
    at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
    at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
    at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
    at kotlinx.coroutines.flow.StateFlowSlot.makePending(StateFlow.kt:286)
    at kotlinx.coroutines.flow.StateFlowImpl.updateState(StateFlow.kt:351)
    at kotlinx.coroutines.flow.StateFlowImpl.setValue(StateFlow.kt:318)
    at com.stripe.android.googlepaylauncher.DefaultGooglePayRepository.isReady$lambda-2(GooglePayRepository.kt:88)
    at com.stripe.android.googlepaylauncher.DefaultGooglePayRepository.$r8$lambda$Am6Oi1LnzZy_OkZq7Memwe57rSE
    at com.stripe.android.googlepaylauncher.DefaultGooglePayRepository$$ExternalSyntheticLambda0.onComplete
    at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8833639/180476630-329fbd33-b0f7-48d9-836d-45a5ff894ab6.png)

@stripe/stripe-react-native@0.14.0

**Comment by xiao555** [comment]
@charliecruzan-stripe Thanks for quick reply!
