### ISSUE TITLE
If the createToken method returns an error, the application quits unexpectedly

### ISSUE THREAD

**Issue by eesttiwar** [stripe/stripe-react-native#1074]
**Describe the bug
If the createToken() method returns an error, the application closes unexpectedly.
I used logcat and this is the error I get when the application crashes:

2022-08-08 15:03:09.451 9520-9685/com.myApp.app E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.myApp.app, PID: 9520
    Request-id: req_qlFYeO9im8AF9l
    com.stripe.android.core.exception.InvalidRequestException: Invalid routing number
        at com.stripe.android.networking.StripeApiRepository.handleApiError(StripeApiRepository.kt:1200)
        at com.stripe.android.networking.StripeApiRepository.makeApiRequest$payments_core_release(StripeApiRepository.kt:1258)
        at com.stripe.android.networking.StripeApiRepository.fetchStripeModel(StripeApiRepository.kt:1229)
        at com.stripe.android.networking.StripeApiRepository.createToken$payments_core_release(StripeApiRepository.kt:635)
        at com.stripe.android.StripeKtxKt.createBankAccountToken(StripeKtx.kt:217)
        at com.reactnativestripesdk.StripeSdkModule$createTokenFromBankAccount$1$1.invokeSuspend(StripeSdkModule.kt:439)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Replay**
1. I make a function called createTokenBankAccount().
2. I make a button where I pass it the function from step 1.
3. I click on the button to activate the function.
4. The whole application closes unexpectedly

**Expected behavior
That it shows me in a console.log() the error

**Desktop (please fill in the following information):** **
 - OPERATING SYSTEM: Windows
 - Version 10 Pro

**Smartphone (please fill in the following information):**
 - Device: Pixel 4 XL
 - OPERATING SYSTEM: Android 
 - Version 11 API 30

React native version:   "~0.63.4",
Stripe version:  "^0.5.0",

My code:

import { useStripe }  from '@stripe/stripe-react-native'

const { createToken } = useStripe();

`const createTokenBankAccount = async() => {
        const data: any = {
            type: 'BankAccount',
            accountHolderName: 'Jenny Rosen',
            accountHolderType: 'individual',
            accountNumber: '000123456789',
            country: 'US',
            currency: 'usd',
            routingNumber: '110000000'
        }
        console.log(data)
        const { error, token } = await createToken(data);

        if (error) {
        Alert.alert(`Error code: ${error.code}`, error.message);
        console.log(`Error: ${JSON.stringify(error)}`);
        } else if (token) {
            setWaitingBankConfirms(false)
            Alert.alert(
                'Success',
                `The token was created successfully! token: ${token.id}`
            );
        }

    }`

@charliecruzan-stripe

**Comment by charliecruzan-stripe** [comment]
Fixed on a more recent version, you'll get an error response back:

<img width="324" alt="Screen Shot 2022-08-09 at 1 30 36 PM" src="https://user-images.githubusercontent.com/97612659/183754926-750ed66c-a974-416a-9de2-d26cc407cc55.png">

Also your `data` payload is incorrect: it should be `Individual` not `individual` (capital "I"). I would avoid using TS's `any` here, and instead use the `Token.CreateParams` type

**Comment by eesttiwar** [comment]
> 
Thank you very much, I upgraded to "^0.5.0", and it even works with the lowercase i.
