### ISSUE TITLE
Android fails to compile after upgrading to 0.18.1

### ISSUE THREAD

**Issue by jkepps** [stripe/stripe-react-native#1134]
**Describe the bug**
I am attempting to upgrade to 0.18.1 in order to [fix iOS builds failing on XCode 14](https://github.com/stripe/stripe-ios/issues/2010#issuecomment-1247207314) with iOS 16 and now my android app will not compile.

**To Reproduce**
`yarn add @stripe/stripe-react-native`
`yarn android`

**Expected behavior**
The android app compiles successfully

**Screenshots**
Error
<img width="1378" alt="Screen Shot 2022-09-14 at 1 40 24 PM" src="https://user-images.githubusercontent.com/11086016/190257949-b595ec82-bbb7-4a85-be01-cdb3a9e43ded.png">

Gradle file
<img width="933" alt="Screen Shot 2022-09-14 at 1 43 48 PM" src="https://user-images.githubusercontent.com/11086016/190258599-294a1df2-6633-4a26-8151-390bf43f657f.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1
 - Version: 0.18.1
 - RN: 0.68.3

**Additional context**
https://github.com/stripe/stripe-ios/issues/1973

**Comment by mballdev** [comment]
Hitting this also

**Comment by charliecruzan-stripe** [comment]
Could you try updating your kotlinVersion to 1.6.21? I'm not able to reproduce this myself, though

**Comment by jkepps** [comment]
ok i think that resolved the issue relating to `stripe-react-native`. I'm now running into this error, but it doesn't seem specific to this repo. seems likely to be an issue with my dev env configuration. closing the issue.

```
> Task :app:devCheckEnvironment FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
36 actionable tasks: 2 executed, 34 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':app:devCheckEnvironment' (type 'CheckEnvironment').
  - Type 'CheckEnvironment' property 'envVars' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'CheckEnvironment' property 'releaseVars' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'CheckEnvironment' property 'serviceVars' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'CheckEnvironment' property 'verifyVarSet' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#missing_annotation for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDevDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':app:devCheckEnvironment' (type 'CheckEnvironment').
  - Type 'CheckEnvironment' property 'envVars' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'CheckEnvironment' property 'releaseVars' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'CheckEnvironment' property 'serviceVars' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'CheckEnvironment' property 'verifyVarSet' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#missing_annotation for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s

    at makeError (/Users/jordanepps/workspace/client/node_modules/execa/index.js:174:9)
    at /Users/jordanepps/workspace/client/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/jordanepps/workspace/client/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/jordanepps/workspace/client/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
