### ISSUE TITLE
Google Pay error [OR_RIBBED_01] in production and in development

### ISSUE THREAD

**Issue by marchingband** [stripe/stripe-react-native#1380]
Using code based on the examples in this repo, I had an application accepted to Google Play Store, expecting the errors that came up in development to resolve when in production, as Google Pay states the flow will only work in a signed production app.

However in production the same error persists. `An unexpected error has occurred. Please try again later. [OR_RIBBED_01]`

I have used Logcat to capture the logs when using the development client I built using EXPO.

```
05-04 10:53:19.048  3615  3911 E Parcel  : Class not found when unmarshalling: com.stripe.android.paymentsheet.PaymentSheetContractV2$Args
05-04 10:53:19.048  3615  3911 E Parcel  : java.lang.ClassNotFoundException: com.stripe.android.paymentsheet.PaymentSheetContractV2$Args
05-04 10:53:19.048  3615  3911 E Parcel  : 	at java.lang.Class.classForName(Native Method)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at java.lang.Class.forName(Class.java:400)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:2517)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at android.os.Parcel.readParcelable(Parcel.java:2471)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at android.os.Parcel.readValue(Parcel.java:2374)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2727)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:269)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at android.os.BaseBundle.getString(BaseBundle.java:992)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at android.content.Intent.getStringExtra(Intent.java:6718)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:336)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1097)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5806)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5611)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:176)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3575)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at android.os.Binder.execTransact(Binder.java:573)
05-04 10:53:19.048  3615  3911 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.stripe.android.paymentsheet.PaymentSheetContractV2$Args
05-04 10:53:19.048  3615  3911 E Parcel  : 	at java.lang.Class.classForName(Native Method)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
05-04 10:53:19.048  3615  3911 E Parcel  : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-04 10:53:19.048  3615  3911 E Parcel  : 	... 16 more
05-04 10:53:19.048  3615  3911 E Parcel  : Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
05-04 10:53:19.050  3615  3911 W Bundle  : Failed to parse Bundle, but defusing quietly
05-04 10:53:19.050  3615  3911 W Bundle  : android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.stripe.android.paymentsheet.PaymentSheetContractV2$Args
05-04 10:53:19.050  3615  3911 W Bundle  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:2545)
05-04 10:53:19.050  3615  3911 W Bundle  : 	at android.os.Parcel.readParcelable(Parcel.java:2471)
05-04 10:53:19.050  3615  3911 W Bundle  : 	at android.os.Parcel.readValue(Parcel.java:2374)
05-04 10:53:19.050  3615  3911 W Bundle  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2727)
05-04 10:53:19.050  3615  3911 W Bundle  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:269)
05-04 10:53:19.050  3615  3911 W Bundle  : 	at android.os.BaseBundle.getString(BaseBundle.java:992)
05-04 10:53:19.050  3615  3911 W Bundle  : 	at android.content.Intent.getStringExtra(Intent.java:6718)
05-04 10:53:19.050  3615  3911 W Bundle  : 	at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:336)
05-04 10:53:19.050  3615  3911 W Bundle  : 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1097)
05-04 10:53:19.050  3615  3911 W Bundle  : 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5806)
05-04 10:53:19.050  3615  3911 W Bundle  : 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5611)
05-04 10:53:19.050  3615  3911 W Bundle  : 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:176)
05-04 10:53:19.050  3615  3911 W Bundle  : 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3575)
05-04 10:53:19.050  3615  3911 W Bundle  : 	at android.os.Binder.execTransact(Binder.java:573)
```

and similar logs around other classes:
`05-04 10:53:59.879  3615  5261 E Parcel  : Class not found when unmarshalling: com.stripe.android.googlepaylauncher.GooglePayPaymentMethodLauncherContract$Args`
`05-04 10:53:26.338  3615  4895 E Parcel  : Class not found when unmarshalling: com.google.android.gms.wallet.shared.BuyFlowConfig`
`05-04 10:53:25.985  3615  5263 E Parcel  : Class not found when unmarshalling: com.stripe.android.googlepaylauncher.GooglePayPaymentMethodLauncherContract$Args`

Any idea what the issue is here?
How can I debug these errors better? The error objects returned from this library contain no useful information that I can see.

**Comment by marchingband** [comment]
I have my app registered with Google Pay.
Of course I have the plugin in app.json
```
    "plugins": [
      [
        "@stripe/stripe-react-native",
        {
          "merchantIdentifier": <merchant_id>,
          "enableGooglePay": true
        }
      ]
    ],

```
I am on v0.23.3 as I believe this is pinned for Expo SDK 48

**Comment by marchingband** [comment]
I have tried 2 approaches to payment.
```
await initStripe({...})
await fetchClientSecret()
await confirmPlatformPayPayment({...})
```
and
```
await initStripe({...})
await fetchClientSecret()
await initPaymentSheet({...})
await presentPaymentSheet()
```
some results on both.

**Comment by charliecruzan-stripe** [comment]
hey @marchingband , i just wanna confirm- you're getting the error code `OR_RIBBED_01`, or was that a typo and it actually reads `OR_BIBED_01`? i think you're getting the latter, but just in case this _is_ a different error code, i want to make sure. These are error codes from Google Pay, not stripe, so I'm not 100% sure about them. i've seen both `OR_BIBED_01` and `OR_BIBED_07` come up in the past, and it's usually down to a mismatch of keys, certs, and the `testEnv` prop (they either **all** have to be for production, or **all** for development). 

as for the `ClassNotFoundException`, your versions look right for SDK 48 🤔 i would make sure that you don't have any other old payments library hanging around that could be pulling in an older version of `stripe-android`

**Comment by marchingband** [comment]
Now that I look closer I get `[OR_BIBED_07]` in production and `[OR_BIBED_01]` in testing, sorry about that 😅
Where are the relevant certs and keys obtained / strored? I didn't encounter info about this when setting up GPAY.

I have `google-services.json`, `GoogleService-Info.plist` as well as `API-XXXXXXXXXXX.json` all sitting in my project from years ago, not sure what's what anymore.

**Comment by charliecruzan-stripe** [comment]
Closing since this is an issue with the google play integration, not a bug with the SDK, but happy to keep helping out as needed @marchingband
