### ISSUE TITLE
Android crash related to CardFieldView

### ISSUE THREAD

**Issue by gpawlik1** [stripe/stripe-react-native#1768]
**Describe the bug**
There is a Android crash being reported that apparently originates from the `CardViewField`. I assume that the solution might be to delay any actions on `ComposeView` until it’s fully attached to the window, potentially using a listener like `ViewTreeObserver.OnGlobalLayoutListener` to ensure the view is attached.

```
 Fatal Exception: java.lang.IllegalStateException: Cannot locate windowRecomposer; View androidx.compose.ui.platform.ComposeView{72bc6f4 V.E...... ......I. 0,0-103,53 #7f0a01ce app:id/icon} is not attached to a window
       at androidx.compose.ui.platform.WindowRecomposer_androidKt.getWindowRecomposer(WindowRecomposer.android.kt:295)
       at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(ComposeView.android.kt:244)
       at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(ComposeView.android.kt:251)
       at androidx.compose.ui.platform.AbstractComposeView.onMeasure(ComposeView.android.kt:288)
       at android.view.View.measure(View.java:25532)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:25532)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1204)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
       at android.view.View.measure(View.java:25532)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:25532)
       at com.reactnativestripesdk.CardFieldView.mLayoutRunnable$lambda$27(CardFieldView.kt:384)
       at com.reactnativestripesdk.CardFieldView.$r8$lambda$tO4Ku94GLM16x8NhrR7Up5q0VFs()
       at com.reactnativestripesdk.CardFieldView$$ExternalSyntheticLambda2.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7886)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:970)
        
```

**Smartphone (please complete the following information):**
 - Device: Model:Motorola One 5G Ace
 - OS: Android 
 - Version 11

**Comment by iM-GeeKy** [comment]
Potentially related to https://github.com/stripe/stripe-react-native/issues/1732#issue-2530364007. @charliecruzan-stripe Is there any update on that issue?

**Comment by tjclawson-stripe** [comment]
Hi @gpawlik1, thanks for reporting. What version of the stripe-react-native SDK are you using and what version of React Native?

**Comment by kaushil111** [comment]
Here is a patch that works with fabric enabled app on Android:

[@stripe-stripe-react-native-npm-0.41.0-7a76d4dacd.patch](https://github.com/user-attachments/files/18552615/%40stripe-stripe-react-native-npm-0.41.0-7a76d4dacd.patch)

It also includes the patch for #1732 with slight modifications. Here is the reference:
https://github.com/stripe/stripe-react-native/issues/1732#issuecomment-2594110710

**Comment by tianzhao-stripe** [comment]
@gpawlik1 

Thank you for the suggestion and your patience! We apologize for the delay in getting back to you. At this time, we are not planning on adding any new features to the Card Element. We are encouraging all users to instead use the Mobile Payment Element, which we launched in 2021. You can find the docs [here](https://docs.stripe.com/payments/accept-a-payment). If there are any reasons the MPE doesn't support your use case, we'd love to hear your feedback!

Thanks, and again apologies for the delays in getting back to you
