### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by martimarkov** [stripe/stripe-react-native#1771]
**Describe the bug**
When adding the library to a clean project the installation fails due to "New Group" folder

**To Reproduce**
1. Setup new project using Yarn 4.5.1
2. run `yarn add @stripe/stripe-react-native`
3. See error

**Expected behavior**
Successful installation.

**Logs**
```
test-stripe-install git:(main) ✗ yarn add @stripe/stripe-react-native
➤ YN0000: · Yarn 4.5.1
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @stripe/stripe-react-native@npm:0.39.0
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ test-stripe-install@workspace:. doesn't provide react (pca0a1), requested by @stripe/stripe-react-native.
➤ YN0002: │ test-stripe-install@workspace:. doesn't provide react-native (p9fb54), requested by @stripe/stripe-react-native.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ A package was added to the project (+ 1.73 MiB).
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0001: │ Error: ENOENT: no such file or directory, lstat 'node_modules/@stripe/stripe-react-native/New Group'
    at Ll (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:4:1321)
    at Object.Z3e (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:4:1589)
    at Zi.lstatSync (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:149:201210)
    at Zi.lstatPromise (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:149:200983)
    at Am.lstatPromise (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:9:2311)
    at ju.lstatPromise (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:9:2311)
    at ju.lstatPromise (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:9:2311)
    at BT (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:4:7280)
    at /Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:4:8451
    at Array.map (<anonymous>)
➤ YN0000: └ Completed
➤ YN0000: · Failed with errors in 0s 189ms
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: ENOENT: no such file or directory, lstat 'node_modules/@stripe/stripe-react-native/New Group'
    at Ll (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:4:1321)
    at Object.Z3e (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:4:1589)
    at Zi.lstatSync (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:149:201210)
    at Zi.lstatPromise (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:149:200983)
    at Am.lstatPromise (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:9:2311)
    at ju.lstatPromise (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:9:2311)
    at ju.lstatPromise (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:9:2311)
    at BT (/Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:4:7280)
    at /Users/xxx/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:4:8451
    at Array.map (<anonymous>) {
  code: 'ENOENT'
}

Node.js v23.0.0
```
**Desktop (please complete the following information):**
 - OS: macOS 15.1
 - Version: 0.39.0

**Comment by sfriedman-stripe** [comment]
Hi @martimarkov, in order for us to better assist you with this integration issue, I'd love to point you to our support channel on [our Discord](https://stripe.com/go/developer-chat), where we have engineers ready to help you 24/5. Thank you!
