### ISSUE TITLE
[Android] : method addObserver must be called on the main thread.

### ISSUE THREAD

**Issue by pritamsoni-hsr** [stripe/stripe-react-native#259]
**Describe the bug**
stripe android not working in an existing project, followed all the instructions as given.

**Screenshots**
![Screenshot_1621796929](https://user-images.githubusercontent.com/23050213/119276459-fedc3680-bc37-11eb-9420-ec2f8d747d7a.png)

**Desktop (please complete the following information):**
 - OS: M1, MacOS, 10.15, node 14.15

**Smartphone (please complete the following information):**
 - Device:  Android emulator, android Q, API version 30

react-native - 0.63

**Additional context**

**Comment by arekkubaczkowski** [comment]
could you share some more details? When it occurs? once application is started or after calling some stripe method?

**Comment by pritamsoni-hsr** [comment]
when the application starts.

**Comment by arekkubaczkowski** [comment]
so it occurs even if you don't `init` sdk by `StripeProvider` or `initStripe` method correct?

**Comment by pritamsoni-hsr** [comment]
nah, I just added the sdk, `npm i`, then `gradlew bundleDebug`, updated build.gradle to 4.x.x.
it builds and when I try to run the code, it loads the js, tried to console log NativeModuels.StripeSdk, js code never gets executed. this is the only screen that I see.
my App code is just this.

`export default () => (<Text>Hello World!</Text>)`

some references that I found 

segmentio/analytics-react-native#255, see this segmentio/analytics-react-native@dac753ad871633e028e1ac6003fbc2a8c263f0c0

dji-sdk/Mobile-SDK-Android#772

[StackOverflow](https://stackoverflow.com/questions/64686001/android-navigation-instrumentation-test-throws-method-addobserver-must-be-called)

**Comment by arekkubaczkowski** [comment]
can you run application via android studio and copy paste some more context of this error from the logcat?

**Comment by pritamsoni-hsr** [comment]
Hi guys, not sure if this will help, 

```sh
2021-05-24 21:57:18.407 12229-12355/com.company.app D/SoLoader: libhermes-executor-debug.so not found on /data/user/0/com.company.app/lib-main
2021-05-24 21:57:18.408 12229-12355/com.company.app D/SoLoader: libhermes-executor-debug.so found on /data/app/~~ddX36iuRxZZJwkr6IGqrpQ==/com.company.app-FK3BPcrOqljytBquyj7yhQ==/lib/x86_64
2021-05-24 21:57:18.408 12229-12355/com.company.app D/SoLoader: Not resolving dependencies for libhermes-executor-debug.so
2021-05-24 21:57:18.424 12229-12355/com.company.app D/SoLoader: Loaded: libhermes-executor-debug.so
2021-05-24 21:57:18.425 12229-12355/com.company.app D/SoLoader: About to load: libfbjni.so
2021-05-24 21:57:18.426 12229-12355/com.company.app D/SoLoader: libfbjni.so not found on /data/user/0/com.company.app/lib-main
2021-05-24 21:57:18.426 12229-12355/com.company.app D/SoLoader: libfbjni.so found on /dat
2021-05-24 21:57:18.426 12229-12355/com.company.app D/SoLoader: Not resolving dependencies for libfbjni.so
2021-05-24 21:57:18.427 12229-12355/com.company.app D/SoLoader: Loaded: libfbjni.so
2021-05-24 21:57:18.631 12229-12355/com.company.app E/unknown:ReactNative: Exception in native call
    java.lang.IllegalStateException: Method addObserver must be called on the main thread
        at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
        at expo.modules.notifications.notifications.service.NotificationsHelper.<init>(NotificationsHelper.java:96)
        at expo.modules.notifications.notifications.handling.NotificationsHandler.<init>(NotificationsHandler.java:60)
        at expo.modules.notifications.NotificationsPackage.createExportedModules(NotificationsPackage.java:33)
        at org.unimodules.adapters.react.ReactModuleRegistryProvider.get(ReactModuleRegistryProvider.java:53)
        at org.unimodules.adapters.react.ModuleRegistryAdapter.createNativeModules(ModuleRegistryAdapter.java:31)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
        at java.lang.Thread.run(Thread.java:920)
2021-05-24 21:57:18.673 12229-12229/com.company.app D/CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10177; state: ENABLED
2021-05-24 21:57:20.459 12229-12322/com.company.app D/EGL_emulation: app_time_stats: avg=338.70ms min=28.59ms max=954.75ms count=3
```

**Comment by pritamsoni-hsr** [comment]
Ok guys, the issue was with `expo-notifications`, I was using an older version.
Closing this issue.

**Comment by miradario** [comment]
I had expo-notification 0.7.2, upgrade it to 0.8.2 works fine
