### ISSUE TITLE
[Android] Cannot find a parameter with this name: returnUrl

### ISSUE THREAD

**Issue by pablogdcr** [stripe/stripe-react-native#397]
**Describe the bug**
When building on Android (`react-native run-android`), it fails with the error below:

```
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (69, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (85, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (108, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (121, 11): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (136, 7): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (187, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (204, 7): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (217, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (235, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (250, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (266, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (282, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (298, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (335, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (351, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (380, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (409, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt: (309, 16): None of the following functions can be called with the arguments supplied:
public final fun confirmPayment(activity: ComponentActivity, confirmPaymentIntentParams: ConfirmPaymentIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
public final fun confirmPayment(fragment: Fragment, confirmPaymentIntentParams: ConfirmPaymentIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt: (313, 13): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt: (405, 14): None of the following functions can be called with the arguments supplied:
public final fun handleNextActionForPayment(activity: ComponentActivity, clientSecret: String, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
public final fun handleNextActionForPayment(fragment: Fragment, clientSecret: String, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt: (434, 14): None of the following functions can be called with the arguments supplied:
public final fun confirmPayment(activity: ComponentActivity, confirmPaymentIntentParams: ConfirmPaymentIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
public final fun confirmPayment(fragment: Fragment, confirmPaymentIntentParams: ConfirmPaymentIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
e: /Users/pablo/Projects/Yego/getyugo_react/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt: (480, 14): None of the following functions can be called with the arguments supplied:
public final fun confirmSetupIntent(activity: ComponentActivity, confirmSetupIntentParams: ConfirmSetupIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
public final fun confirmSetupIntent(fragment: Fragment, confirmSetupIntentParams: ConfirmSetupIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe

FAILURE: Build failed with an exception.
```

**To Reproduce**
1. Install the library
2. Run the build on Android
3. See the error

**Expected behavior**
Build and run on Android

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Version 11.4

**Comment by thorsten-stripe** [comment]
@PabloGiraudCarrier can you provide your code? Does it build fine on iOS?

**Comment by PabloGiraudCarrier** [comment]
Hi, it builds fine on IOS yes.
I just created an app from scratch (`react-native init Test`), installed the library (`npm i @stripe/stripe-react-native`)
And then build (`react-native run-android`)

```
➜  Test react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
(node:6676) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Jetifier found 896 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :app:compileDebugJavaWithJavac

> Task :app:stripDebugDebugSymbols
Unable to strip the following libraries, packaging them as they are: libc++_shared.so, libevent-2.1.so, libevent_core-2.1.so, libevent_extra-2.1.so, libfb.so, libfbjni.so, libflipper.so, libfolly_futures.so, libfolly_json.so, libglog.so, libglog_init.so, libhermes-executor-common-debug.so, libhermes-executor-common-release.so, libhermes-executor-debug.so, libhermes-executor-release.so, libhermes-inspector.so, libimagepipeline.so, libjsc.so, libjscexecutor.so, libjsijniprofiler.so, libjsinspector.so, libnative-filters.so, libnative-imagetranscoder.so, libreact_codegen_reactandroidspec.so, libreact_nativemodule_core.so, libreactnativeblob.so, libreactnativejni.so, libreactnativeutilsjni.so, libreactperfloggerjni.so, libturbomodulejsijni.so, libyoga.so.

> Task :app:installDebug
Installing APK 'app-debug.apk' on 'Redmi Note 9S - 10' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL in 1m 1s
29 actionable tasks: 29 executed
info Connecting to the development server...
8081
info Starting the app on "a5f12580"...
Starting: Intent { cmp=com.test/.MainActivity }
➜  Test npm i @stripe/stripe-react-native

added 122 packages, and audited 1115 packages in 21s

88 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  Test react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
(node:6744) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Jetifier found 915 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...

> Task :stripe_stripe-react-native:compileDebugKotlin FAILED
38 actionable tasks: 30 executed, 8 up-to-date
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (69, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (85, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (108, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (121, 11): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (136, 7): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (187, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (204, 7): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (217, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (235, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (250, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (266, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (282, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (298, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (335, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (351, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (380, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (409, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt: (309, 16): None of the following functions can be called with the arguments supplied:
public final fun confirmPayment(activity: ComponentActivity, confirmPaymentIntentParams: ConfirmPaymentIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
public final fun confirmPayment(fragment: Fragment, confirmPaymentIntentParams: ConfirmPaymentIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt: (313, 13): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt: (405, 14): None of the following functions can be called with the arguments supplied:
public final fun handleNextActionForPayment(activity: ComponentActivity, clientSecret: String, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
public final fun handleNextActionForPayment(fragment: Fragment, clientSecret: String, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt: (434, 14): None of the following functions can be called with the arguments supplied:
public final fun confirmPayment(activity: ComponentActivity, confirmPaymentIntentParams: ConfirmPaymentIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
public final fun confirmPayment(fragment: Fragment, confirmPaymentIntentParams: ConfirmPaymentIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt: (480, 14): None of the following functions can be called with the arguments supplied:
public final fun confirmSetupIntent(activity: ComponentActivity, confirmSetupIntentParams: ConfirmSetupIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
public final fun confirmSetupIntent(fragment: Fragment, confirmSetupIntentParams: ConfirmSetupIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_stripe-react-native:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 43s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (69, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (85, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (108, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (121, 11): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (136, 7): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (187, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (204, 7): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (217, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (235, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (250, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (266, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (282, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (298, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (335, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (351, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (380, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt: (409, 9): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt: (309, 16): None of the following functions can be called with the arguments supplied:
public final fun confirmPayment(activity: ComponentActivity, confirmPaymentIntentParams: ConfirmPaymentIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
public final fun confirmPayment(fragment: Fragment, confirmPaymentIntentParams: ConfirmPaymentIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt: (313, 13): Cannot find a parameter with this name: returnUrl
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt: (405, 14): None of the following functions can be called with the arguments supplied:
public final fun handleNextActionForPayment(activity: ComponentActivity, clientSecret: String, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
public final fun handleNextActionForPayment(fragment: Fragment, clientSecret: String, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt: (434, 14): None of the following functions can be called with the arguments supplied:
public final fun confirmPayment(activity: ComponentActivity, confirmPaymentIntentParams: ConfirmPaymentIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
public final fun confirmPayment(fragment: Fragment, confirmPaymentIntentParams: ConfirmPaymentIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
e: /Users/pablo/Projects/Yego/Test/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt: (480, 14): None of the following functions can be called with the arguments supplied:
public final fun confirmSetupIntent(activity: ComponentActivity, confirmSetupIntentParams: ConfirmSetupIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe
public final fun confirmSetupIntent(fragment: Fragment, confirmSetupIntentParams: ConfirmSetupIntentParams, stripeAccountId: String? = ...): Unit defined in com.stripe.android.Stripe

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_stripe-react-native:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 43s

    at makeError (/Users/pablo/Projects/Yego/Test/node_modules/execa/index.js:174:9)
    at /Users/pablo/Projects/Yego/Test/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async runOnAllDevices (/Users/pablo/Projects/Yego/Test/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/pablo/Projects/Yego/Test/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.
```

**Comment by PabloGiraudCarrier** [comment]
I've tested it on another computer and it builds.
However, instead of the error `Cannot find a parameter with this name: returnUrl`, I still have a warning saying that the parameter returnUrl is deprecated and that it will be removed in the next major version.

**Comment by souhe** [comment]
I'm glad you managed to finally build the app @pablogdcr.

But you're right, `customUrl` was deprecated in Android SDK in version 16.8.0 for some payment methods. The information about it can be found here - https://github.com/stripe/stripe-android/blob/master/CHANGELOG.md

@thorsten-stripe let's fix it and remove the usage of deprecated parameters since it will be removed in the future versions of stripe-android SDK.

**Comment by pablogdcr** [comment]
Unfortunately, I'm still not able to build on my current computer.
The only difference that I can see between my two computers is the version of node that I'm using (16.4.2 on this computer, 16.1.0 on the computer where the build succeed).

Can the error be due to this?
I don't understand why I have this build error when the error is related to the Android SDK, which does not depend on the computer but on the version used in the package.

**Comment by souhe** [comment]
@pablogdcr are you testing exactly the same project (same repo) on both devices? Or maybe you created the project separately on the second computer?
Node version should not matter

**Comment by pablogdcr** [comment]
Yes, exact same repo.

The issue is solved now, I upgraded my react-native version from 0.63.x to 0.64.x today, and now it builds fine.
I suppose that something was wrong with the dependencies installed on this computer and that the problem has been solved by reinstalling everything correctly.

Thanks a lot for your help, let's hope that the problem doesn't come back and that no one else faces it!
