### ISSUE TITLE
App crashing after using createPaymentMethod

### ISSUE THREAD

**Issue by BogdanVV** [stripe/stripe-react-native#834]
The application crashes after confirming the card data entered in CardField with createPaymentMethod({ type: 'Card' }).
This issue also appears on the plain RN application created with npx react-native init *project_name* with only stripe-react-native 0.3.0 installed.
The previous build of my app (before updating stripe-react-native to 0.3.0) works fine with the same code.

1. Enter all test card stripe data into the <CardField /> (e.g. card number: 4242 4242 4242 4242)
2. Activate the function that invokes createPaymentMethod({ type: 'Card })
4. See the app crashed without showing any error.

 - OS: Windows 10

 - Device: Android Studio emulator, API 30
 - OS: Android

Here's the actual code:

```
const App: () => Node = () => {
  const { createPaymentMethod } = useStripe();

  const handleTest = () => {
    createPaymentMethod({
      type: 'Card'
    })
      .then(res => {
        console.log('res', res)
      })
  };

  const cardContainerStyle = {
    width: '100%',
    height: 48,
    marginTop: 8,
  };

  return (
    <StripeProvider
      publishableKey="****"
    >
      <View style={{ flex: 1 }}>
        <CardField
          postalCodeEnabled={false}
          style={cardContainerStyle}
        />
        <Pressable onPress={handleTest}>
          <Text style={{ marginVertical: 20, textAlign: 'center', borderWidth: 1 }}>Test stripe</Text>
        </Pressable>
      </View>
    </StripeProvider>
  );
};
```

**Comment by charliecruzan-stripe** [comment]
Can you get the crash logs by running `adb logcat` and then triggering the app crash? there should be a fatal exception somewhere in there that will give us more information

**Comment by BogdanVV** [comment]
> Can you get the crash logs by running `adb logcat` and then triggering the app crash? there should be a fatal exception somewhere in there that will give us more information

03-10 10:14:15.934  5876  5949 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
03-10 10:14:15.934  5876  5949 E AndroidRuntime: Process: com.****************, PID: 5876
03-10 10:14:15.934  5876  5949 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/stripe/android/core/exception/InvalidRequestException;
03-10 10:14:15.934  5876  5949 E AndroidRuntime:        at com.reactnativestripesdk.ErrorsKt.createError(Errors.kt:75)
03-10 10:14:15.934  5876  5949 E AndroidRuntime:        at com.reactnativestripesdk.StripeSdkModule$createPaymentMethod$1.onError(StripeSdkModule.kt:388)
03-10 10:14:15.934  5876  5949 E AndroidRuntime:        at com.stripe.android.Stripe$dispatchResult$2.invokeSuspend(Stripe.kt:1663)
03-10 10:14:15.934  5876  5949 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
03-10 10:14:15.934  5876  5949 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
03-10 10:14:15.934  5876  5949 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
03-10 10:14:15.934  5876  5949 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
03-10 10:14:15.934  5876  5949 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
03-10 10:14:15.934  5876  5949 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7656)
03-10 10:14:15.934  5876  5949 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-10 10:14:15.934  5876  5949 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-10 10:14:15.934  5876  5949 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
03-10 10:14:15.934  5876  5949 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.stripe.android.core.exception.InvalidRequestException" on path: DexPat
hList[[zip file "/data/app/~~iPBWjOct2pC4VJEb7iYFPw==/com.vacation_rental_rn2-Juu9zPTnuacrgV7etfyIOg==/base.apk"],nativeLibraryDirectories=[/data/app/~~iPBWjOct2pC4VJEb7iYFPw==/com.vacati
on_rental_rn2-Juu9zPTnuacrgV7etfyIOg==/lib/x86, /data/app/~~iPBWjOct2pC4VJEb7iYFPw==/com.vacation_rental_rn2-Juu9zPTnuacrgV7etfyIOg==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]

**Comment by charliecruzan-stripe** [comment]
Closing for inactivity- it looks from the logs like this is due to an older version of stripe-android being pinned in the project
