### ISSUE TITLE
`Card details not complete` when confirming a setup intent, using PaymentSheet

### ISSUE THREAD

**Issue by 256hz** [stripe/stripe-react-native#859]
**Describe the bug**
I'm using the PaymentSheet to collect card details.  We're using setup intents as we intend to process the payment later.  We are able to create the intent and collect the card details, but when I use `confirmSetupIntent`, I get the error from the title:

```
{
  "code": "Failed",
  "declineCode": null,
  "localizedMessage": "Card details not complete",
  "message": "Card details not complete",
  "stripeErrorCode": null,
  "type": null,
}
```

I'm getting `confirmSetupIntent` from the `useStripe` hook:

```js
const { confirmSetupIntent } = useStripe();
```

Without confirming the setup intent, the card isn't saved and the payment won't be processed.

**To Reproduce**
1. Create setup intent.
2. Initialize payment sheet with setup intent.
3. Collect card details.
4. Confirm setup intent.

**Expected behavior**
The setup intent is confirmed without error.

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS 15.3.1
 - React Native 0.64.2
 - Stripe SDK 0.3.0

**Additional context**
I looked into the iOS/Android code and I think this isn't supported by the SDK.  The `PaymentMethodFactory` that is responsible for creating `paymentMethodParams` only seems to take a CardFormView or a CardFieldView.  It doesn't check for values in the PaymentSheet.

Is there another way to confirm the SetupIntent?  The PaymentSheet is important for our business needs.

**Comment by 256hz** [comment]
`confirmSetupIntent` actually crashes Android, which could be a separate issue.

- Device: Samsung Galaxy S10
- OS: Android 11
- RN 0.64.2
- Stripe 0.3.0

Stack trace:
```
E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Could not invoke StripeSdk.confirmSetupIntent
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:246)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:246) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/stripe/android/core/exception/InvalidRequestException;
        at com.reactnativestripesdk.ErrorsKt.createError(Errors.kt:75)
        at com.reactnativestripesdk.StripeSdkModule.confirmSetupIntent(StripeSdkModule.kt:602)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:246) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.stripe.android.core.exception.InvalidRequestException" on path: DexPathList[[zip file "/data/app/~~RbEGsoKdRrtuNQmsF3SPjQ==/org.treecard.app.development-sLpmCI14MsLml3Frj6RR7Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~RbEGsoKdRrtuNQmsF3SPjQ==/org.treecard.app.development-sLpmCI14MsLml3Frj6RR7Q==/lib/arm64, /data/app/~~RbEGsoKdRrtuNQmsF3SPjQ==/org.treecard.app.development-sLpmCI14MsLml3Frj6RR7Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.reactnativestripesdk.ErrorsKt.createError(Errors.kt:75) 
        at com.reactnativestripesdk.StripeSdkModule.confirmSetupIntent(StripeSdkModule.kt:602) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:246) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:923) 
```

**Comment by franciscofernandez0** [comment]
Hello, we have a similar problem with confirmPayment.

We want allow users retry after fail 3DS. After store client_secret ant token we want to show up confirmPayment in a new screen.

With react-native-stripe 0.1.4 this is not possible because the confirmPayment method is attached to the cardField element. Until cardfiled is not complete confirmPayment throws this error, and we are sending a token...

¿Anyone know how to fix it?

**Comment by 256hz** [comment]
Can anyone from Stripe comment on whether we can use Setup Intents with the PaymentSheet?  We would like to save cards for future transactions using the Payment Sheet, and are wondering if this is possible.

**Comment by charliecruzan-stripe** [comment]
Hi! Sorry, lost track of this issue :( 

You can indeed use setupintents with the paymentsheet. I think the problem here is your are attempting to use `confirmSetupIntent`, where you should be using `confirmPaymentSheetPayment` (or you can confirm outside of the client app, see the [docs](https://stripe.com/docs/payments/save-and-reuse?platform=react-native) for more details on that and the rest of the flow)

**Comment by 256hz** [comment]
Oh perfect, thanks @charliecruzan-stripe!  That makes sense, just didn't think of it.

**Comment by charliecruzan-stripe** [comment]
No worries, im wondering if there's a way we could get rid of the need for that and instead just save whether or not you had a payment sheet flow open before calling `confirmPayment` or `confirmSetupIntent`, but would have to handle the off chance that someone does that flow but then confirms a _separate_ payment/setup intent

**Comment by 256hz** [comment]
Yeah, it would be more intuitive for them to work regardless of component, but I'm sure it's not easy on your end. It wasn't immediately obvious to me how wiring up `confirmPayment` and `confirmSetupIntent` to the payment sheet would work.

**Comment by charliecruzan-stripe** [comment]
Gotchya, I have a todo item to update the doc strings for all the components/methods, so you should have to rely less on the actual integration docs and get a better idea of exactly what to do right in your editor. This will be at the top of that list!

**Comment by gavortex** [comment]
Token error: {"code": "Failed", "declineCode": null, "localizedMessage": "Card details not complete", "message": "Card details not complete", "stripeErrorCode": null, "type": null}
 ERROR  ❌ Card payment error: [Error: Card details not complete]   Need help here. I can't seem to overcome this error with Stripe  using   @stripe/stripe-react-native@0.37.0  or version: 0.50.3   "react-native": "0.81.5",  "expo": "~54.0.30",

**Comment by gbirch-stripe** [comment]
Hi @gavortex, could you please open a new issue with full repro steps, OS, etc.?

**Comment by gavortex** [comment]
Thanks a lot but iwas able to fix the issue.   I will post the fix if someone else has the same issue in the futire.
    On Monday, March 16, 2026 at 01:40:00 PM EDT, George Birch ***@***.***> wrote:  
 
 gbirch-stripe left a comment (stripe/stripe-react-native#859)
Hi @gavortex, could you please open a new issue with full repro steps, OS, etc.?
